# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  build-for-macoc:
    macos:
      xcode: "11.3.0"
    steps:
      - checkout
      - run: make -C ./tests/

  build-for-linux:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi

    docker:
      - image: cimg/node:14.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: g++ src/night.cpp

  build-for-windows:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: g++ src/night.cpp

workflows:
  version: 2.1
  build:
    jobs:
      -build-for-linux
      - build-for-windows
